POST http://localhost:3003/api/blogs
Content-Type: application/json
# Authorization: Bearer add token
{
"title": "This is a new test and I check if this works still", 
"author": "Test author",
"url": "ThisIsTooTestUrl.com",
"likes": 15,
"userId": "65afabc20826dacec65c44c5"
}